on : push

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      -name: checkout repository
      -uses: actions/checkoutsv2

      -name: setup Python
      -uses: actions/setup-python@v2
      with:
        python-version: 3.10
      
      -name: Install dependencies
       run: | 
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      -name: test with Pytest
       run: |
         python -m pytest --cov=inflamations.models tests/test_models.py

